# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- production

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: InstallSSHKey@0 # 导入SSH
  inputs:
    knownHostsEntry: 'github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXMyxtm4k540cjx+PI86+utYDzVhBsxIlomreI4vJMTyGJpKuyIMgcxrDPLJfzFYkE1d66FeORp3R0QpX/A6jfHoKdGKekL4OyB5hAp5sCWZKXuKMe1Sf5h02LaCk83tRePed4BlctNLvsEwzguB8U1uylZRdQQWu2P9V6LhVQrzisJ40Gc667ni3R3mwRU9+2bTlKp5QvZJMdqHgE0mPRuAtPd6KzYDzBS6Ceh8hoUT4tJZUKXyq83vOP0hGq6HltWfbg9wej1J22qhqDbb21YR5J/rSx0MDXunlGnrnWWgTAu+5wNgW3Vw2LycNJGV8MDnj30hGZM/oT18d35v43 T460@DESKTOP-2VRPNO7'
    sshKeySecureFile: 'id_rsa'
  displayName: 'Installing SSH...'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g hexo-cli
    hexo deploy
  displayName: 'npm install and build, hexo deploy'