# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- production

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g hexo-cli
    git config --global user.name "Azure DevOps"
    git config --global user.email "mail.chewei@gmail.com"
    hexo config deploy.repository git@github.com:ThisWayne/thiswayne.github.io.git
    hexo deploy
  displayName: 'npm install and build, hexo deploy'